variables:
  CI_PROJECT_ID_PKG_LINUX: 2491
  CI_PROJECT_ID_PKG_RESCTL_DEMO: 2482

stages:
  - docker
  - build

.deploy_snippet: &deploy
  - >
    if [ "${CI_COMMIT_BRANCH}" == "master" ]; then
      eval $(ssh-agent -s)
      chmod 0600 ${DEPLOY_SSH_KEY}
      ssh-add ${DEPLOY_SSH_KEY}
      scp -oStrictHostKeyChecking=no ${IMAGE}.img.gz facebook@images.collabora.co.uk:images/
      scp -oStrictHostKeyChecking=no ${IMAGE}.img.gz.sha256 facebook@images.collabora.co.uk:images/
      scp -oStrictHostKeyChecking=no ${IMAGE}.img.bmap facebook@images.collabora.co.uk:images/
      scp -oStrictHostKeyChecking=no ${IMAGE}.vmdk facebook@images.collabora.co.uk:images/
      scp -oStrictHostKeyChecking=no ${IMAGE}.vmdk.gz facebook@images.collabora.co.uk:images/
      scp -oStrictHostKeyChecking=no "latest-version.txt" facebook@images.collabora.co.uk:images/
    fi

.deploy_ec2_ami_snippet: &deploy_ec2_ami
  - >
    if [ "${CI_COMMIT_BRANCH}" == "master" ]; then
      python3 ../aws-ec2/upload-image-aws-ec2.py --ami-name="resctl-demo/bullseye/${VERSION}" --ami-description="resctl-demo version ${VERSION}" --image-file="${IMAGE}.vmdk"
    fi

docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.16.0
    entrypoint: [""]
  tags:
    - lightweight
  script:
    - |
      cat << EOF > /kaniko/.docker/config.json
      {
        "auths":{
          "$CI_REGISTRY": {
            "username":"$CI_REGISTRY_USER",
            "password":"$CI_REGISTRY_PASSWORD"
          }
        }
      }
      EOF
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/ci-image-builder/Dockerfile
      --destination $CI_REGISTRY_IMAGE/ci-image-builder:$CI_COMMIT_REF_SLUG
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --single-snapshot

build:
  stage: build
  image:
    name: $CI_REGISTRY_IMAGE/ci-image-builder:$CI_COMMIT_REF_SLUG
    entrypoint: [""]
  tags:
    - kvm
  stage: build
  script:
    - echo "Downloading packages from CI"
    - 'curl --location --output pkg-linux.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.collabora.com/api/v4/projects/${CI_PROJECT_ID_PKG_LINUX}/jobs/artifacts/debian/master/download?job=build"'
    - 'curl --location --output pkg-resctl-demo.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.collabora.com/api/v4/projects/${CI_PROJECT_ID_PKG_RESCTL_DEMO}/jobs/artifacts/debian/master/download?job=build"'
    - unzip \*.zip && rm *.zip
    - mv artifacts/ debs/

    - echo "Downloading linux payload"
    - 'curl --location --output linux.tar.xz "https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.8.11.tar.xz"'
    - xz -d linux.tar.xz
    - mv linux.tar overlays/resctl-demo/usr/local/resctl-demo

    - export VERSION="$(date '+%Y%m%d.%H%M%S')-${CI_COMMIT_SHORT_SHA}"
    - export IMAGE="resctl-demo-image_${VERSION}"
    - mkdir out && cd out
    - echo ${VERSION} > latest-version.txt
    - debos --scratchsize=16G ../resctl-demo-ospack.yaml
    - debos -t "image:${IMAGE}" ../resctl-demo-image.yaml
    - *deploy
    - *deploy_ec2_ami
