stages:
  - docker
  - build

.deploy_snippet: &deploy
  - >
    if [ "${CI_COMMIT_BRANCH}" = "${CI_DEFAULT_BRANCH}" -o "${CI_BUILD_REF_NAME}" = "${CI_COMMIT_TAG}" ] ; then
      # copy readme into images directory
      cp README.md out/

      # create symbolic link to latest version
      cd "${CWD}"
      mkdir "resctl-demo-${VERSION}"
      mv out/* resctl-demo-${VERSION}/
      ln -Tsf "resctl-demo-${VERSION}" "resctl-demo-latest"

      # create symbolic link to commit tag
      if [ ! -z "${CI_COMMIT_TAG}" ] ; then
        ln -Tsf "resctl-demo-${VERSION}" "resctl-demo-${CI_COMMIT_TAG}"
      fi

      # remove un-needed files
      rm -f resctl-demo-*.yaml resctl-demo-${VERSION}/*.img

      # install ssh key
      eval $(ssh-agent -s)
      chmod 0600 ${DEPLOY_SSH_KEY}
      ssh-add ${DEPLOY_SSH_KEY}

      # copy files to images dump
      rsync -a -e "ssh -oStrictHostKeyChecking=no" resctl-demo-* facebook@images.collabora.co.uk:images/
    fi

.deploy_ec2_ami_snippet: &deploy_ec2_ami
  - >
    if [ "${CI_COMMIT_BRANCH}" = "$CI_DEFAULT_BRANCH" -o "${CI_BUILD_REF_NAME}" = "${CI_COMMIT_TAG}" ] ; then
      # upload legacyboot image to AWS
      cd "${CWD}"
      python3 aws-ec2/upload-image-aws-ec2.py --ami-name="resctl-demo/bookworm/${VERSION}" --ami-description="resctl-demo version ${VERSION}" --image-file="out/${IMAGE_LEGACY}.vmdk"
    fi

docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.16.0
    entrypoint: [""]
  tags:
    - lightweight
  script:
    - |
      cat << EOF > /kaniko/.docker/config.json
      {
        "auths":{
          "$CI_REGISTRY": {
            "username":"$CI_REGISTRY_USER",
            "password":"$CI_REGISTRY_PASSWORD"
          }
        }
      }
      EOF
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/ci-image-builder/Dockerfile
      --destination $CI_REGISTRY_IMAGE/ci-image-builder:$CI_COMMIT_REF_SLUG
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --single-snapshot

build:
  stage: build
  image:
    name: $CI_REGISTRY_IMAGE/ci-image-builder:$CI_COMMIT_REF_SLUG
    entrypoint: [""]
  tags:
    - kvm
  stage: build
  script:
    - export CWD=$(pwd)
    - export VERSION="${CI_BUILD_REF_NAME}-$(date '+%Y%m%d.%H%M%S')-${CI_COMMIT_SHORT_SHA}"
    - export IMAGE_LEGACY="resctl-demo-image-legacyboot"
    - export IMAGE_EFI="resctl-demo-image-efiboot"
    - export IMAGE_EFI_FLASHER="resctl-demo-flasher-efiboot"
    - mkdir out && cd out
    - echo ${VERSION} > version.txt
    - debos --scratchsize=16G ../resctl-demo-ospack.yaml
    - debos -t "image:${IMAGE_LEGACY}" ../resctl-demo-image-legacyboot.yaml
    - debos -t "image:${IMAGE_EFI}" ../resctl-demo-image-efiboot.yaml
    - debos -t "image:${IMAGE_EFI_FLASHER}" -t "flash_image:${IMAGE_EFI}" ../resctl-demo-flasher-efiboot.yaml
    - *deploy_ec2_ami
    - *deploy
