name: Build resctl-demo images
on:
  pull_request:
  push:
  # Build every 1st day of the month since artifacts only last 90-days
  schedule:
    - cron: "* * 1 * *"
  workflow_dispatch:

jobs:
  build_image:
    strategy:
      fail-fast: false
      matrix:
        variant:
          - resctl-demo
          - resctl-demo-meta
    name: Build ${{ matrix.variant }} image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y debian-archive-keyring \
                                  debos \
                                  libostree-dev \
                                  qemu-utils

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: Install debos from source
        run: |
          go install github.com/go-debos/debos/cmd/debos@main
          sudo -H ln -sf $HOME/go/bin/debos /usr/bin/debos

      - name: Download kernel
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: iocost-benchmark/resctl-demo-linux
          branch: resctl-demo
          workflow: ci.yaml
          workflow_conclusion: success
          path: debs/

      - name: Massage downloaded files
        run: |
          mv debs/resctl-demo-kernel/* debs/
          find debs

      - name: Build image
        run: |
          mkdir out
          sudo debos --disable-fakemachine --artifactdir=out --template-var=variant:${{ matrix.variant }} --scratchsize=16G resctl-demo-ospack.yaml
          sudo debos --disable-fakemachine --artifactdir=out --template-var=variant:${{ matrix.variant }} resctl-demo-image-legacyboot.yaml
          sudo debos --disable-fakemachine --artifactdir=out --template-var=variant:${{ matrix.variant }} resctl-demo-image-efiboot.yaml
          sudo debos --disable-fakemachine --artifactdir=out --template-var=variant:${{ matrix.variant }} resctl-demo-flasher-efiboot.yaml

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.variant }}
          path: |
            out/
            !out/*.img
          if-no-files-found: error
